name: Update Toolchains

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at 00:00 UTC.
  workflow_dispatch:     # Allow manual triggering.

permissions:
  contents: write
  pull-requests: write

jobs:
  update-toolchains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/update-nightly@320a06a6647c90ac97452b20fad5b689905a9791
        with:
          token: ${{ secrets.RBMT_PRS }}
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/update-stable@320a06a6647c90ac97452b20fad5b689905a9791
        with:
          token: ${{ secrets.RBMT_PRS }}
